development:
  storage:
    adapter: memory
  index_path: index
  
test:
  storage:
    adapter: memory
  index_path: index_test

production:
  storage:
    adapter: postgres
    user: root
    pass: 